### ISSUE TITLE
The app isn't hugely responsive

### ISSUE THREAD

**Issue by oliverjam** [FAC10/week3-PAMF#72]
Your user story says: "I want to be able to play this on the move, as well as at home"

But the site is quite hard to use at smaller screen sizes. It might be better if the gifs stacked into a column rather than squeezing into the narrow width.

**Comment by oliverjam** [comment]
![screener_20170310 11-04-55](https://cloud.githubusercontent.com/assets/9408641/23793073/8fe46228-0581-11e7-8d49-e3d1e792695d.png)

**Comment by pbywater** [comment]
fixed!
