### ISSUE TITLE
Should remove Futura font file

### ISSUE THREAD

**Issue by yvonne-liu** [FAC10/week3-PAMF#86]
Two issues: 

1. The font works but it's giving you an error in the console, I don't know why 
2. You should probably not be distributing a copyrighted/non-free font file in your repo because currently it's available to everyone to get a copy of it -- probably not the best.

**Comment by pbywater** [comment]
Agreed - it works on mac because it's a font we automatically have. The font file actually doesn't do anything I think. Gonna get rid of it :):)
